name: update README
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: check, generate and update
    runs-on: ubuntu-latest

    steps:
      - name: pulling repo.
        uses: actions/checkout@v4

      - name: setting up bun.
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: installing dependencies.
        run: bun install

      - name: build
        run: |
          bun run build

      - name: Commiting the updated file to readme.
        env:
          GITHUB_ACTION: "true"
        run: |
          sudo chmod +x .scripts/
          ./.scripts/commit-updated-readme.sh
